# Generated by Django 3.0.5 on 2024-01-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0003_auto_20240123_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(upload_to='Imagenes/'),
        ),
    ]
