# Generated by Django 3.0.5 on 2024-01-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0004_auto_20240123_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.FileField(upload_to='galeria/camisas/'),
        ),
    ]
