# Generated by Django 5.0.7 on 2024-07-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0004_alter_image_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
