# Generated by Django 3.0.5 on 2024-01-24 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0006_auto_20240123_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('camisas', 'Camisas'), ('remeras', 'Remeras')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
