# Generated by Django 3.0.5 on 2024-01-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0007_image_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('camisas', 'Camisas'), ('remeras', 'Remeras')], max_length=100),
        ),
    ]
