# Generated by Django 5.0.7 on 2024-07-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0007_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
