# Generated by Django 3.0.5 on 2024-01-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0008_auto_20240124_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('camisas', 'Camisas'), ('remeras', 'Remeras'), ('camperas', 'Camperas')], max_length=100),
        ),
    ]
