# Generated by Django 5.0.7 on 2024-07-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0009_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
