# Generated by Django 3.0.5 on 2024-01-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0009_auto_20240124_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('camisas', 'Camisas'), ('remeras', 'Remeras'), ('hoodie', 'Hoodie'), ('pantalones', 'Pantalones'), ('shorts', 'Shorts'), ('camperas', 'Camperas'), ('zapatillas', 'Zapatillas'), ('botas', 'Botas')], max_length=100),
        ),
    ]
