# Generated by Django 3.0.5 on 2024-01-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0012_auto_20240124_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('camisas', 'Camisas'), ('remeras', 'Remeras'), ('hoodies', 'Hoodies'), ('pantalones', 'Pantalones'), ('shorts', 'Shorts'), ('camperas', 'Camperas'), ('zapatillas', 'Zapatillas'), ('botas', 'Botas'), ('blusas', 'Blusas'), ('vestidos', 'Vestidos'), ('faldas', 'Faldas'), ('pantalonesf', 'Pantalonesf'), ('shortsf', 'Shortsf'), ('camperasf', 'Camperasf'), ('zapatillasf', 'Zapatillasf'), ('botasf', 'Botasf'), ('lanzamientos', 'Lanzamientos'), ('galerias', 'Galerias')], max_length=100),
        ),
    ]
