# Generated by Django 5.0.7 on 2024-07-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0013_auto_20240124_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('camisas', 'Camisas'), ('remeras', 'Remeras'), ('hoodies', 'Hoodies'), ('pantalones', 'Pantalones'), ('shorts', 'Shorts'), ('camperas', 'Camperas'), ('zapatillas', 'Zapatillas'), ('botas', 'Botas'), ('blusas', 'Blusas'), ('vestidos', 'Vestidos'), ('faldas', 'Faldas'), ('pantalonesf', 'Pantalonesf'), ('shortsf', 'Shortsf'), ('camperasf', 'Camperasf'), ('zapatillasf', 'Zapatillasf'), ('botasf', 'Botasf'), ('carteleras', 'carteleras'), ('galerias', 'Galerias')], max_length=100),
        ),
    ]
